version: "3.7"
services:
#  db:
#    image: postgres:15
#    container_name: db_app
#    command: -p 5435
#    expose:
#      - 5435
#    env_file:
#      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: interview_preparation_app
    command: ["/interview_preparation/docker/app.sh"]
    ports:
      - 7878:8000
    depends_on:
#      - db
      - redis
