"""tp

Revision ID: 83d76d2516f8
Revises:
Create Date: 2023-10-05 11:56:53.456493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d76d2516f8'
down_revision: Union[str, None] = '64784d669e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
